import React, { createContext, useContext, useState, useEffect } from 'react';

// Demo data - 50 diverse products for buyers (stored locally)
const initialProducts = [
  // Electronics & Tech
  {
    id: '1',
    name: 'Apple iPad (Gen 10)',
    category: 'Electronics',
    price: 499,
    description: 'Latest generation iPad with advanced features and stunning display.',
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400',
    stock: 2,
    initialStock: 10,
    sellerId: 'demo-seller-1',
    sellerName: 'Tech Store',
  },
  {
    id: '2',
    name: 'Samsung Galaxy S23',
    category: 'Electronics',
    price: 999,
    description: 'Premium Android smartphone with exceptional camera capabilities.',
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400',
    stock: 1,
    initialStock: 5,
    sellerId: 'demo-seller-2',
    sellerName: 'Mobile Hub',
  },
  {
    id: '3',
    name: 'Dell XPS 15',
    category: 'Electronics',
    price: 1799,
    description: 'Premium laptop with stunning 4K display and powerful performance.',
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400',
    stock: 1,
    initialStock: 3,
    sellerId: 'demo-seller-3',
    sellerName: 'Computer World',
  },
  {
    id: '4',
    name: 'Apple iMac 2023',
    category: 'Electronics',
    price: 2196,
    description: 'All-in-one desktop with M3 chip and stunning 24-inch display.',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400',
    stock: 3,
    initialStock: 5,
    sellerId: 'demo-seller-1',
    sellerName: 'Tech Store',
  },
  {
    id: '5',
    name: 'Logitech MX Master 3S',
    category: 'Accessories',
    price: 99,
    description: 'Ergonomic wireless mouse with precision tracking and long battery life.',
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400',
    stock: 15,
    initialStock: 20,
    sellerId: 'demo-seller-4',
    sellerName: 'Accessory Shop',
  },
  {
    id: '6',
    name: 'AirPods Pro (2nd Gen)',
    category: 'Accessories',
    price: 249,
    description: 'Wireless earbuds with active noise cancellation and spatial audio.',
    imageUrl: 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=400',
    stock: 8,
    initialStock: 8,
    sellerId: 'demo-seller-2',
    sellerName: 'Mobile Hub',
  },
  {
    id: '7',
    name: 'MacBook Pro 14" M3',
    category: 'Electronics',
    price: 1999,
    description: 'Professional laptop with M3 chip, perfect for creative work.',
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400',
    stock: 2,
    initialStock: 4,
    sellerId: 'demo-seller-1',
    sellerName: 'Tech Store',
  },
  {
    id: '8',
    name: 'Sony WH-1000XM5',
    category: 'Accessories',
    price: 399,
    description: 'Premium noise-cancelling headphones with exceptional sound quality.',
    imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400',
    stock: 5,
    initialStock: 8,
    sellerId: 'demo-seller-5',
    sellerName: 'Audio Central',
  },
  {
    id: '9',
    name: 'Nintendo Switch OLED',
    category: 'Electronics',
    price: 349,
    description: 'Gaming console with vibrant OLED screen and portable design.',
    imageUrl: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400',
    stock: 3,
    initialStock: 6,
    sellerId: 'demo-seller-6',
    sellerName: 'Game Zone',
  },
  {
    id: '10',
    name: 'Canon EOS R6 Mark II',
    category: 'Electronics',
    price: 2499,
    description: 'Professional mirrorless camera with 24.2MP sensor and 4K video.',
    imageUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400',
    stock: 1,
    initialStock: 2,
    sellerId: 'demo-seller-7',
    sellerName: 'Photo Pro',
  },

  // Books & Education
  {
    id: '11',
    name: 'Clean Code by Robert Martin',
    category: 'Books',
    price: 35,
    description: 'Essential programming book for writing maintainable code.',
    imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400',
    stock: 12,
    initialStock: 15,
    sellerId: 'demo-seller-8',
    sellerName: 'Book Haven',
  },
  {
    id: '12',
    name: 'The Psychology of Money',
    category: 'Books',
    price: 18,
    description: 'Timeless lessons on wealth, greed, and happiness.',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    stock: 8,
    initialStock: 10,
    sellerId: 'demo-seller-8',
    sellerName: 'Book Haven',
  },
  {
    id: '13',
    name: 'Atomic Habits by James Clear',
    category: 'Books',
    price: 22,
    description: 'An easy and proven way to build good habits and break bad ones.',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400',
    stock: 6,
    initialStock: 8,
    sellerId: 'demo-seller-9',
    sellerName: 'Study Corner',
  },
  {
    id: '14',
    name: 'Calculus Textbook (3rd Edition)',
    category: 'Books',
    price: 85,
    description: 'Comprehensive calculus textbook for university students.',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    stock: 4,
    initialStock: 6,
    sellerId: 'demo-seller-9',
    sellerName: 'Study Corner',
  },
  {
    id: '15',
    name: 'Introduction to Algorithms',
    category: 'Books',
    price: 95,
    description: 'The definitive guide to algorithms and data structures.',
    imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400',
    stock: 3,
    initialStock: 5,
    sellerId: 'demo-seller-8',
    sellerName: 'Book Haven',
  },

  // Clothing & Fashion
  {
    id: '16',
    name: 'Nike Air Max 270',
    category: 'Clothing',
    price: 150,
    description: 'Comfortable running shoes with Max Air cushioning.',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    stock: 7,
    initialStock: 10,
    sellerId: 'demo-seller-10',
    sellerName: 'Fashion Forward',
  },
  {
    id: '17',
    name: 'Levi\'s 501 Original Jeans',
    category: 'Clothing',
    price: 89,
    description: 'Classic straight-fit jeans in authentic denim.',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400',
    stock: 5,
    initialStock: 8,
    sellerId: 'demo-seller-10',
    sellerName: 'Fashion Forward',
  },
  {
    id: '18',
    name: 'Uniqlo Heattech Long Sleeve',
    category: 'Clothing',
    price: 25,
    description: 'Warm thermal base layer perfect for winter.',
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    stock: 12,
    initialStock: 15,
    sellerId: 'demo-seller-11',
    sellerName: 'Style Hub',
  },
  {
    id: '19',
    name: 'Adidas Originals Hoodie',
    category: 'Clothing',
    price: 65,
    description: 'Classic three-stripe hoodie in comfortable cotton blend.',
    imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400',
    stock: 4,
    initialStock: 6,
    sellerId: 'demo-seller-11',
    sellerName: 'Style Hub',
  },
  {
    id: '20',
    name: 'Ray-Ban Aviator Sunglasses',
    category: 'Clothing',
    price: 180,
    description: 'Iconic aviator sunglasses with UV protection.',
    imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400',
    stock: 2,
    initialStock: 4,
    sellerId: 'demo-seller-10',
    sellerName: 'Fashion Forward',
  },

  // Beauty & Personal Care
  {
    id: '21',
    name: 'The Ordinary Niacinamide 10%',
    category: 'Beauty',
    price: 8,
    description: 'Serum for reducing blemishes and balancing oil production.',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400',
    stock: 15,
    initialStock: 20,
    sellerId: 'demo-seller-12',
    sellerName: 'Beauty Box',
  },
  {
    id: '22',
    name: 'CeraVe Foaming Facial Cleanser',
    category: 'Beauty',
    price: 12,
    description: 'Gentle foaming cleanser for normal to oily skin.',
    imageUrl: 'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400',
    stock: 8,
    initialStock: 12,
    sellerId: 'demo-seller-12',
    sellerName: 'Beauty Box',
  },
  {
    id: '23',
    name: 'Olaplex No.3 Hair Perfector',
    category: 'Beauty',
    price: 28,
    description: 'At-home treatment for damaged and compromised hair.',
    imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400',
    stock: 6,
    initialStock: 8,
    sellerId: 'demo-seller-13',
    sellerName: 'Hair Care Plus',
  },
  {
    id: '24',
    name: 'Fenty Beauty Pro Filt\'r Foundation',
    category: 'Beauty',
    price: 35,
    description: 'Longwear foundation with soft matte finish.',
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400',
    stock: 4,
    initialStock: 6,
    sellerId: 'demo-seller-13',
    sellerName: 'Hair Care Plus',
  },
  {
    id: '25',
    name: 'Glossier Boy Brow',
    category: 'Beauty',
    price: 18,
    description: 'Tinted brow gel for fuller-looking eyebrows.',
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400',
    stock: 10,
    initialStock: 12,
    sellerId: 'demo-seller-12',
    sellerName: 'Beauty Box',
  },

  // Home & Garden
  {
    id: '26',
    name: 'IKEA FADO Table Lamp',
    category: 'Home & Garden',
    price: 25,
    description: 'Minimalist spherical table lamp with warm glow.',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    stock: 8,
    initialStock: 10,
    sellerId: 'demo-seller-14',
    sellerName: 'Home Decor',
  },
  {
    id: '27',
    name: 'Philips Hue Smart Bulb',
    category: 'Home & Garden',
    price: 45,
    description: 'Smart LED bulb with 16 million colors and app control.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    stock: 6,
    initialStock: 8,
    sellerId: 'demo-seller-14',
    sellerName: 'Home Decor',
  },
  {
    id: '28',
    name: 'Succulent Plant Set (3 Pack)',
    category: 'Home & Garden',
    price: 18,
    description: 'Three small succulents in decorative pots.',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    stock: 12,
    initialStock: 15,
    sellerId: 'demo-seller-15',
    sellerName: 'Green Thumb',
  },
  {
    id: '29',
    name: 'Bamboo Cutting Board Set',
    category: 'Home & Garden',
    price: 35,
    description: 'Set of 3 bamboo cutting boards in different sizes.',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
    stock: 5,
    initialStock: 7,
    sellerId: 'demo-seller-15',
    sellerName: 'Green Thumb',
  },
  {
    id: '30',
    name: 'Essential Oil Diffuser',
    category: 'Home & Garden',
    price: 32,
    description: 'Ultrasonic diffuser with LED lights and timer.',
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    stock: 4,
    initialStock: 6,
    sellerId: 'demo-seller-14',
    sellerName: 'Home Decor',
  },

  // Sports & Outdoors
  {
    id: '31',
    name: 'Yoga Mat Premium',
    category: 'Sports & Outdoors',
    price: 45,
    description: 'Non-slip yoga mat with carrying strap.',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    stock: 8,
    initialStock: 10,
    sellerId: 'demo-seller-16',
    sellerName: 'Fit Life',
  },
  {
    id: '32',
    name: 'Resistance Bands Set',
    category: 'Sports & Outdoors',
    price: 22,
    description: 'Set of 5 resistance bands with door anchor.',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    stock: 12,
    initialStock: 15,
    sellerId: 'demo-seller-16',
    sellerName: 'Fit Life',
  },
  {
    id: '33',
    name: 'Water Bottle Insulated',
    category: 'Sports & Outdoors',
    price: 28,
    description: '32oz stainless steel bottle keeps drinks cold for 24 hours.',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400',
    stock: 6,
    initialStock: 8,
    sellerId: 'demo-seller-17',
    sellerName: 'Outdoor Gear',
  },
  {
    id: '34',
    name: 'Running Headphones Wireless',
    category: 'Sports & Outdoors',
    price: 65,
    description: 'Sweat-proof wireless earbuds for active lifestyle.',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
    stock: 4,
    initialStock: 6,
    sellerId: 'demo-seller-17',
    sellerName: 'Outdoor Gear',
  },
  {
    id: '35',
    name: 'Foam Roller for Recovery',
    category: 'Sports & Outdoors',
    price: 35,
    description: 'High-density foam roller for muscle recovery.',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    stock: 7,
    initialStock: 9,
    sellerId: 'demo-seller-16',
    sellerName: 'Fit Life',
  },

  // Toys & Games
  {
    id: '36',
    name: 'Chess Set Premium Wood',
    category: 'Toys & Games',
    price: 85,
    description: 'Handcrafted wooden chess set with storage box.',
    imageUrl: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=400',
    stock: 3,
    initialStock: 5,
    sellerId: 'demo-seller-18',
    sellerName: 'Game Master',
  },
  {
    id: '37',
    name: 'Jenga Classic Game',
    category: 'Toys & Games',
    price: 25,
    description: 'Classic wooden block stacking game for all ages.',
    imageUrl: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400',
    stock: 8,
    initialStock: 10,
    sellerId: 'demo-seller-18',
    sellerName: 'Game Master',
  },
  {
    id: '38',
    name: 'Rubik\'s Cube Speed',
    category: 'Toys & Games',
    price: 15,
    description: 'Professional speed cube for competitive solving.',
    imageUrl: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400',
    stock: 12,
    initialStock: 15,
    sellerId: 'demo-seller-19',
    sellerName: 'Puzzle Palace',
  },
  {
    id: '39',
    name: 'Cards Against Humanity',
    category: 'Toys & Games',
    price: 30,
    description: 'Party game for horrible people. Ages 17+.',
    imageUrl: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400',
    stock: 5,
    initialStock: 7,
    sellerId: 'demo-seller-19',
    sellerName: 'Puzzle Palace',
  },
  {
    id: '40',
    name: 'LEGO Architecture Set',
    category: 'Toys & Games',
    price: 45,
    description: 'Build iconic landmarks with this detailed LEGO set.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    stock: 4,
    initialStock: 6,
    sellerId: 'demo-seller-18',
    sellerName: 'Game Master',
  },

  // Health & Wellness
  {
    id: '41',
    name: 'Digital Kitchen Scale',
    category: 'Health & Wellness',
    price: 25,
    description: 'Precise digital scale for cooking and portion control.',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
    stock: 6,
    initialStock: 8,
    sellerId: 'demo-seller-20',
    sellerName: 'Health Hub',
  },
  {
    id: '42',
    name: 'Meditation Cushion Set',
    category: 'Health & Wellness',
    price: 55,
    description: 'Comfortable zafu and zabuton for meditation practice.',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    stock: 3,
    initialStock: 5,
    sellerId: 'demo-seller-20',
    sellerName: 'Health Hub',
  },
  {
    id: '43',
    name: 'Sleep Eye Mask Silk',
    category: 'Health & Wellness',
    price: 18,
    description: 'Silk eye mask for better sleep and relaxation.',
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    stock: 10,
    initialStock: 12,
    sellerId: 'demo-seller-21',
    sellerName: 'Wellness World',
  },
  {
    id: '44',
    name: 'Bluetooth Sleep Headphones',
    category: 'Health & Wellness',
    price: 35,
    description: 'Comfortable headband with built-in speakers for sleep.',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
    stock: 4,
    initialStock: 6,
    sellerId: 'demo-seller-21',
    sellerName: 'Wellness World',
  },
  {
    id: '45',
    name: 'Essential Oil Starter Kit',
    category: 'Health & Wellness',
    price: 42,
    description: 'Set of 6 essential oils with diffuser and guide.',
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    stock: 5,
    initialStock: 7,
    sellerId: 'demo-seller-20',
    sellerName: 'Health Hub',
  },

  // Automotive
  {
    id: '46',
    name: 'Car Phone Mount Magnetic',
    category: 'Automotive',
    price: 22,
    description: 'Strong magnetic phone mount for car dashboard.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    stock: 8,
    initialStock: 10,
    sellerId: 'demo-seller-22',
    sellerName: 'Auto Accessories',
  },
  {
    id: '47',
    name: 'Car Air Freshener Set',
    category: 'Automotive',
    price: 12,
    description: 'Set of 3 natural car air fresheners in different scents.',
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    stock: 15,
    initialStock: 18,
    sellerId: 'demo-seller-22',
    sellerName: 'Auto Accessories',
  },
  {
    id: '48',
    name: 'Car Charger USB-C Fast',
    category: 'Automotive',
    price: 18,
    description: 'Fast charging USB-C car charger with dual ports.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    stock: 6,
    initialStock: 8,
    sellerId: 'demo-seller-23',
    sellerName: 'Tech Auto',
  },
  {
    id: '49',
    name: 'Car Seat Covers Set',
    category: 'Automotive',
    price: 45,
    description: 'Universal car seat covers in black neoprene.',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
    stock: 3,
    initialStock: 5,
    sellerId: 'demo-seller-23',
    sellerName: 'Tech Auto',
  },
  {
    id: '50',
    name: 'Car Emergency Kit',
    category: 'Automotive',
    price: 35,
    description: 'Complete emergency kit with jumper cables and tools.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    stock: 4,
    initialStock: 6,
    sellerId: 'demo-seller-22',
    sellerName: 'Auto Accessories',
  },
];

const ProductContext = createContext();

export const useProducts = () => {
  const context = useContext(ProductContext);
  if (!context) {
    throw new Error('useProducts must be used within a ProductProvider');
  }
  return context;
};

export const ProductProvider = ({ children }) => {
  const [products, setProducts] = useState(initialProducts);
  const [loading, setLoading] = useState(false);

  const addProduct = (newProduct, sellerId = null, sellerName = null) => {
    // Add to local state only (no Firebase)
    const productWithSeller = { 
      ...newProduct, 
      id: `product_${Date.now()}`, // Generate unique ID
      sellerId: sellerId, 
      sellerName: sellerName,
      initialStock: newProduct.stock,
      createdAt: new Date().toISOString(),
    };
    setProducts(prev => [productWithSeller, ...prev]);
  };

  const updateProduct = (productId, updatedProduct) => {
    // Update local state only
    setProducts(prev => 
      prev.map(product => 
        product.id === productId ? { ...product, ...updatedProduct, updatedAt: new Date().toISOString() } : product
      )
    );
  };

  const deleteProduct = (productId) => {
    // Delete from local state only
    setProducts(prev => prev.filter(product => product.id !== productId));
  };

  const getUserProducts = (userId = 'current-user') => {
    // Return products created by the current user (for seller dashboard)
    if (userId && userId !== 'current-user') {
      return products.filter(p => p.sellerId === userId);
    }
    // For demo purposes, return all products if no userId provided
    return products;
  };

  const getAllProducts = () => {
    // Return all products from all sellers (for main marketplace)
    return products;
  };

  const value = {
    products,
    loading,
    addProduct,
    updateProduct,
    deleteProduct,
    getUserProducts,
    getAllProducts,
  };

  return (
    <ProductContext.Provider value={value}>
      {children}
    </ProductContext.Provider>
  );
};
